# Symfony 4 services.yaml file for Riprap.

# Riprap-specific parameters start here.
parameters:
    app.fixity.eventtype.uri: 'http://id.loc.gov/vocabulary/preservation/eventType/fix'
    app.fixity.eventtype.code: 'fix'

    app.service.detailmanager.delimiter: ';'

    # To not register any fetchresourcelist plugins, use app.plugins.fetchresourcelist []
    # app.plugins.fetchresourcelist: ['app:riprap:plugin:fetchresourcelist:from:file']
    app.plugins.fetchresourcelist.from.file.paths: ['resources/riprap_resource_ids.txt']

    # Settings for the app:riprap:plugin:fetchresourcelist:from:drupal plugin.
    app.plugins.fetchresourcelist: ['app:riprap:plugin:fetchresourcelist:from:drupal']
    app.plugins.fetchresourcelist.from.drupal.baseurl: 'http://localhost:8000'
    app.plugins.fetchresourcelist.from.drupal.json_authorization_headers: ['Authorization: Basic YWRtaW46aXNsYW5kb3Jh'] # admin:islandora
    app.plugins.fetchresourcelist.from.drupal.use_fedora_urls: true
    app.plugins.fetchresourcelist.from.drupal.media_auth: ['admin', 'islandora']
    app.plugins.fetchresourcelist.from.drupal.content_types: ['islandora_object']
    app.plugins.fetchresourcelist.from.drupal.media_tags: ['/taxonomy/term/15']
    app.plugins.fetchresourcelist.from.drupal.gemini_endpoint: 'http://localhost:8000/gemini' 
    # For now, will need to be replaced pending outcome of https://github.com/mjordan/riprap/issues/21.
    app.plugins.fetchresourcelist.from.drupal.gemini_auth_header: 'Bearer islandora'

    # To not register any fetchdigest plugins, use app.plugins.fetchdigest [].
    # Currently we only allow one fetchdigest plugin per fixity event (i.e., this
    # value is not an array).
    app.plugins.fetchdigest: 'app:riprap:plugin:fetchdigest:from:fedoraapi'
    app.fixity.fetchdigest.from.fedoraapi.method: 'HEAD'
    app.fixity.fetchdigest.from.fedoraapi.algorithm: 'SHA-1'    

    # To not register any persist plugins, use app.plugins.persist []
    app.plugins.persist: ['app:riprap:plugin:persist:to:database']
  
    # To not register any postcheck plugins, use app.plugins.postcheck []
    app.plugins.postcheck: ['app:riprap:plugin:postcheck:mailfailures', 'app:riprap:plugin:postcheck:migratefedora3auditlog']
    app.plugins.postcheck.mailfailures.from: 'from@example.com'
    app.plugins.postcheck.mailfailures.to: 'to@example.com'

    # Set to 'disabled' in production.
    app.mockrepository: 'enabled'

    ### 'filesystemexample' plugins
    # app.plugins.fetchresourcelist: ['app:riprap:plugin:fetchresourcelist:from:glob']
    # app.plugins.fetchresourcelist.from.glob.file_directory: 'resources/filesystemexample/resourcefiles'
    # app.plugins.fetchdigest: 'app:riprap:plugin:fetchdigest:from:shell'
    # app.plugins.fetchdigrest.from.shell.command: '/usr/bin/sha1sum'
    # app.plugins.persist: ['app:riprap:plugin:persist:to:csv']
    # app.plugins.postcheck: ['app:riprap:plugin:postcheck:sayhi']


### Do not modify any of the values below this line.
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
